### ISSUE TITLE
Null Safe

### ISSUE THREAD

**Issue by billylev** [shawnlauzon/latLngToTimezone#2]
Please upgrade library to be null safe.

**Comment by shawnlauzon** [comment]
Thank you for the reminder. This is a PR to do this which I looked at briefly, but didn't quite follow how this resolved null safety (because I haven't yet read about it in detail).

If you have some time, could you look at the PR and let me know what you think?

**Comment by billylev** [comment]
Looking briefly, doesn't look done to me, Im only seeing the flutter version updated. It's actually very easy to do with the tools yourself, especially as you have no dependancies. Run 'flutter upgrade' on stable channel to upgrade to 2.0.3. Then when it's done, run 'dart migrate'. It will analyse the code and show you a link. Open the link and it shows you what it needs changing. In your case takes a while to load lat_lng_to_timezone.dart as it large. It suggests 3053 added checks. Hit 'Apply Migration' button at the top. Run a test. I've done this to a number of my projects - works very well. 

If you do have dependancies do these 2 first, and it will list what libs have been migrated, and then apply the changes for you. 
flutter pub outdated --mode=null-safety
flutter pub upgrade --null-safety 

Good work by the way. Useful library for timezones.

**Comment by shawnlauzon** [comment]
Fantastic, thank you for the steps. I'll look into it.

> Good work by the way. Useful library for timezones.

Very useful! But I can't take the credit, I just ported it from someone else for my Flutter project :)

**Comment by shawnlauzon** [comment]
Actually that was a great PR. Closing this issue as fixed with PR#1
